### ISSUE TITLE
jupyterlab markdown and raw cell error

### ISSUE THREAD

**Issue by saffaalvi** [StatCan/kubeflow-containers#77] opened 2020-07-21 17:40 UTC
When a new markdown or raw cell are added to a notebook, an error repeatedly pops up every time you try to interact with the cell:

<img width="1411" alt="errorconsole" src="https://user-images.githubusercontent.com/57377830/88084635-b30dbc00-cb52-11ea-8f2d-959454edadf8.png">

I've tried this with 3 images: `minimal-notebook-cpu`, `machine-learning-notebook-cpu`, and `geomatics-notebook-cpu` and they all had the same problem. This only seems to be a problem with newly created notebook servers as it was tested with a notebook from ~2 weeks ago and a `machine-leaning-notebook-cpu` from 43 days ago and no errors came up. 

The commit SHA for the working `machine-learning-notebook-cpu` is 562fa4a2899eeb9ae345c51c2491447ec31a87d7

**Comment by ca-scribner** [comment] 2020-07-21 18:06
To reproduce this, if you create a markdown cell you have to wait a moment for the error to show.  If you create a markdown cell and immediately populate it, the error wont come up

**Comment by sylus** [comment] 2020-07-22 15:22
https://github.com/kubeflow-kale/kale/issues/165

**Comment by sylus** [comment] 2020-07-22 15:34
I just merged a PR that temporarily reverts Kale, new containers should be rdy in an hour.

**Comment by saffaalvi** [comment] 2020-07-24 19:40
I made the change to use `jlpm` instead of `npm` in the `minimal-notebook/cpu/Dockerfile` and `minimal-notebook/gpu/Dockerfile` which can be seen in https://github.com/StatCan/kubeflow-containers/compare/746d058e2f37e004da5ca483d121bfb9e0545f2b...e760c19cf5676a08b2477142e9cd460c45d90700 (can ignore `FROM base` change as local image was used to build the container).

The issue with the markdown and raw cells was still there even after these changes were made.

**Comment by saffaalvi** [comment] 2020-07-27 19:40
Looks like the LPS extension is actually throwing the error here which is triggering kale's handler to display the dialog with the error message.

An issue was previously created by @sylus on kubeflow-kale's Github page: https://github.com/kubeflow-kale/kale/issues/165 and I have created an issue for this on the jupyterlab-lps Github page as well: https://github.com/krassowski/jupyterlab-lsp/issues/299

For now if we want to use the kale extension, a quick fix would be to just disable LSP when running kale.

**Comment by sylus** [comment] 2020-08-06 02:38
This is now fixed upstream, can we test now?

**Comment by saffaalvi** [comment] 2020-08-06 21:25
When creating a new server with the custom image `http://k8scc01covidacr.azurecr.io/minimal-notebook-cpu:6fa16e8f0d1534d2b39e0fece7f2147442fcd0db`, when a new notebook with Python3 is created, the following error appears:

<img width="1387" alt="RPC" src="https://user-images.githubusercontent.com/57377830/89583902-2842e780-d809-11ea-91ff-dba50c95c0f6.png">

When a new notebook with Go, Julia, Python 3.7, and R is created, the above error appears as well as a new error: 

<img width="876" alt="error" src="https://user-images.githubusercontent.com/57377830/89584126-8ec80580-d809-11ea-8ec7-57e5b1034744.png">

**Comment by sylus** [comment] 2020-08-07 01:48
Yeah confirmed probably should rename this issue since is slightly different now.

**Comment by sylus** [comment] 2020-08-07 05:08
I think this should fix it:

https://github.com/StatCan/kubeflow-containers/pull/88

Pushed a test and seems to have fixed when deployed.

**Comment by sylus** [comment] 2020-08-07 14:23
I'm going to close this out please open a new issue if problem persists am doing the building of containers right now

**Closed by sylus** 2020-08-07 14:23 UTC
Labels: component/jupyter, kind/bug, priority/blocker, triage/blocked
